### ISSUE TITLE
KeyError: 'VTimeLLMConfig'

### ISSUE THREAD

**Issue by zipMunk** [huangb23/VTimeLLM#40]
I encountered an error when I try to run the offline_demo by this instruction:
`python -m vtimellm.inference --model_base <path to the Vicuna v1.5 weights> `

I choose the weights from vtimellm-vicuna-v1-5-7b-stage3.

These are messages:

Loading VTimeLLM from base model...
Traceback (most recent call last):
  File "/amax/data/maopengzhe/envs/vtimellm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/amax/data/maopengzhe/envs/vtimellm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/amax/data/maopengzhe/projects/VTimeLLM/vtimellm/inference.py", line 78, in <module>
    tokenizer, model, context_len = load_pretrained_model(args, args.stage2, args.stage3)
  File "/amax/data/maopengzhe/projects/VTimeLLM/vtimellm/model/builder.py", line 34, in load_pretrained_model
    tokenizer = AutoTokenizer.from_pretrained(model_base, use_fast=False)
  File "/amax/data/maopengzhe/envs/vtimellm/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 718, in from_pretrained
    tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
  File "/amax/data/maopengzhe/envs/vtimellm/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 663, in __getitem__
    model_type = self._reverse_config_mapping[key.__name__]
KeyError: 'VTimeLLMConfig'

It seems that There are some errors about the base model. How can I solve the problem?

**Comment by qingyunyanran** [comment]
I face the same problem, how do you solve it?

**Comment by qingyunyanran** [comment]
(base) root@autodl-container-02b744a905-5ba14402:~/VTimeLLM# python -m vtimellm.inference --model_base /root/VTimeLLM/checkpoints/vtimellm-vicuna-v1-5-7b/vtimellm-vicuna-v1-5-7b-stage1
Loading VTimeLLM from base model...
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/VTimeLLM/vtimellm/inference.py", line 78, in <module>
    tokenizer, model, context_len = load_pretrained_model(args, args.stage2, args.stage3)
  File "/root/VTimeLLM/vtimellm/model/builder.py", line 34, in load_pretrained_model
    tokenizer = AutoTokenizer.from_pretrained(model_base, use_fast=False)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 718, in from_pretrained
    tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 663, in __getitem__
    model_type = self._reverse_config_mapping[key.__name__]
KeyError: 'VTimeLLMConfig'

**Comment by runchar** [comment]
Hello, the  `--model_base <path to the Vicuna v1.5 weights>`  refer to the path to the `pytorch_model-00001-of-00002.bin`...
If you have same file structure with docs/train.md, the the model_base path is `checkpoints/vicuna-7b-v1.5`
```
- VTimeLLM
    - checkpoints
        - clip
        	- ViT-L-14.pt
        - vicuna-7b-v1.5                        <-- This is the 'model_base'  
        	- pytorch_model-00001-of-00002.bin
        	- ...
    - data
        - blip_laion_cc_sbu_558k.json
        - stage2.json
        - stage3.json
    - scripts
    	- stage1.sh
    	- stage2.sh
    	- stage3.sh
    	- ...
    - vtimellm
    - ...
```
